[Telegram]
; Получить можно отсюда: https://my.telegram.org/apps.
API_ID = your_api_id
API_HASH = your_api_hash
PHONE_NUMBER = +1234567890

[Bot]
; Интервал между загрузкой чатов.
INTERVAL_CHAT = 1
; Интервал между удалением сообщений.
INTERVAL_MESSAGE = 0.5
; Ограничение сообщений по времени (сообщения нельзя редактировать после 48 часов).
LIMIT_HOURS = 0
; Лимит сообщений для загрузки; 0 - без лимита.
COUNT_MESSAGES = 1000
; Список ID чатов для зачистки (можно указать @юзернейм).
CHATS_ID = @USERNAME,-1001234567890,1234567890
; Текст для замены.
TEXT_REPLACE = .
